/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Controladores.CtrlConfiguracion;
import Modelos.ConfiguracionDAO;

/**
 *
 * @author afane
 */
public class FrmConfiguracion extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmConfiguracion
     */
    public FrmConfiguracion() {
        initComponents();
        
        ConfiguracionDAO configuracionDAO = new ConfiguracionDAO();
    new CtrlConfiguracion(this, configuracionDAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPorcentajeGanancia = new javax.swing.JComboBox<>();
        cbIvaPredeterminado = new javax.swing.JComboBox<>();
        cbDescuentoMaximo = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 244, 248));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Configuración del Sistema");
        setPreferredSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbPorcentajeGanancia.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbPorcentajeGanancia.setForeground(new java.awt.Color(51, 51, 51));
        cbPorcentajeGanancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbPorcentajeGanancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 120, 150, 32));

        cbIvaPredeterminado.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbIvaPredeterminado.setForeground(new java.awt.Color(51, 51, 51));
        cbIvaPredeterminado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbIvaPredeterminado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 150, 32));

        cbDescuentoMaximo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbDescuentoMaximo.setForeground(new java.awt.Color(51, 51, 51));
        cbDescuentoMaximo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbDescuentoMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 150, 32));

        btnGuardar.setBackground(new java.awt.Color(45, 74, 138));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar Configuración");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.setFocusPainted(false);
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 180, 42));

        btnRestaurar.setBackground(new java.awt.Color(255, 255, 255));
        btnRestaurar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRestaurar.setForeground(new java.awt.Color(45, 74, 138));
        btnRestaurar.setText("Restaurar Valores");
        btnRestaurar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRestaurar.setFocusPainted(false);
        getContentPane().add(btnRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 160, 42));

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(230, 51, 51));
        btnCerrar.setText("Cerrar");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setFocusPainted(false);
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 120, 42));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 74, 138));
        jLabel1.setText("CONFIGURACIÓN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 74, 138));
        jLabel2.setText("Porcentaje de ganancia para precio de venta (%):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 74, 138));
        jLabel3.setText("IVA predeterminado (%):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 74, 138));
        jLabel4.setText("Descuento máximo permitido (%):  ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnRestaurar;
    public javax.swing.JComboBox<String> cbDescuentoMaximo;
    public javax.swing.JComboBox<String> cbIvaPredeterminado;
    public javax.swing.JComboBox<String> cbPorcentajeGanancia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
