/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

import Controladores.ctrlProductos.NuevoProductoController;
import Controladores.ctrlProductos.GestionProductosController;
import Controladores.ctrlProductos.AjusteInventarioController;
import Modelos.Roles;
import Modelos.Usuario;

/**
 *
 * @author ASUS
 */
public class MDI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MDI.class.getName());
    public static JDesktopPane jDesktopPane_MDI;

    public MDI() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("SIGVET");

        this.setLayout(null);
        jDesktopPane_MDI = new JDesktopPane();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_MDI.setBounds(0, 0, ancho, (alto));
        this.add(jDesktopPane_MDI);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu_proveedores = new javax.swing.JMenu();
        jMenuItem_nuevo_proveedor = new javax.swing.JMenuItem();
        jMenuItem_gestionar_proveedores = new javax.swing.JMenuItem();
        jMenu_producto = new javax.swing.JMenu();
        jMenuItem_nuevo_producto = new javax.swing.JMenuItem();
        jMenuItem_gestionar_producto = new javax.swing.JMenuItem();
        jMenuItem_ajuste_inventario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu_proveedores.setText("Proveedores");

        jMenuItem_nuevo_proveedor.setText("Nuevo Proveedor");
        jMenuItem_nuevo_proveedor.addActionListener(this::jMenuItem_nuevo_proveedorActionPerformed);
        jMenu_proveedores.add(jMenuItem_nuevo_proveedor);

        jMenuItem_gestionar_proveedores.setText("Gestionar Proveedores");
        jMenuItem_gestionar_proveedores.addActionListener(this::jMenuItem_gestionar_proveedoresActionPerformed);
        jMenu_proveedores.add(jMenuItem_gestionar_proveedores);

        jMenuBar1.add(jMenu_proveedores);
        jMenu_proveedores.add(jMenuItem_nuevo_proveedor);

        jMenuItem_gestionar_proveedores.setText("Gestionar Proveedores");
        jMenu_proveedores.add(jMenuItem_gestionar_proveedores);

        jMenuBar1.add(jMenu_proveedores);

        jMenu_producto.setText("Producto");

        jMenuItem_nuevo_producto.setText("Nuevo Producto");
        jMenuItem_nuevo_producto.addActionListener(this::jMenuItem_nuevo_productoActionPerformed);
        jMenu_producto.add(jMenuItem_nuevo_producto);

        jMenuItem_gestionar_producto.setText("Gestion Productos");
        jMenuItem_gestionar_producto.addActionListener(this::jMenuItem_gestionar_productoActionPerformed);
        jMenu_producto.add(jMenuItem_gestionar_producto);

        jMenuItem_ajuste_inventario.setText("Ajuste de Inventario");
        jMenuItem_ajuste_inventario.addActionListener(this::jMenuItem_ajuste_inventarioActionPerformed);
        jMenu_producto.add(jMenuItem_ajuste_inventario);

        jMenuBar1.add(jMenu_producto);

        jMenu2.setText("Usuarios");

        jMenuItem2.setText("Nuevo Usuario");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Gestionar Usuarios");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Roles y Permisos");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Vistas.FrmRolesPermisos roles = new Vistas.FrmRolesPermisos();
        FrmNuevoUsuario usuarios = new FrmNuevoUsuario();
        Modelos.Roles rol = new Modelos.Roles();
        Modelos.RolesDAO dao = new Modelos.RolesDAO();
        Modelos.UsuarioDAO daoUsuario = new Modelos.UsuarioDAO();
        Usuario usuario = new Usuario();
        Controladores.CtrlRoles.CtrlGestionarRoles controlador = new Controladores.CtrlRoles.CtrlGestionarRoles(rol, roles, usuarios, dao);
        Controladores.CtrlUsuarios.CtrlNuevoUsuario controladorUsuario = new Controladores.CtrlUsuarios.CtrlNuevoUsuario(usuario, usuarios, daoUsuario);
        jDesktopPane_MDI.add(usuarios);
        usuarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Modelos.Usuario usuario = new Modelos.Usuario();
        FrmGestionarUsuarios gestionarUsuarios = new FrmGestionarUsuarios();
        Modelos.UsuarioDAO usuarioDAO = new Modelos.UsuarioDAO();
        Controladores.CtrlUsuarios.CtrlGestionarUsuarios ctrl = new Controladores.CtrlUsuarios.CtrlGestionarUsuarios(usuario, gestionarUsuarios, usuarioDAO);
        
        ctrl.cargarTabla();
        jDesktopPane_MDI.add(gestionarUsuarios);
        gestionarUsuarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        FrmRolesPermisos roles = new FrmRolesPermisos();
        jDesktopPane_MDI.add(roles);
        roles.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem_nuevo_proveedorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_nuevo_proveedorActionPerformed
        // TODO add your handling code here:
        Vistas.FrmNuevoProveedor form = new Vistas.FrmNuevoProveedor();
        Modelos.Proveedor proveedor = new Modelos.Proveedor();
        Modelos.ProveedorDAO dao = new Modelos.ProveedorDAO();
        Controladores.CtrlProveedor.CtrlNuevoProveedor ctrl = new Controladores.CtrlProveedor.CtrlNuevoProveedor(
                proveedor, form, dao);

        jDesktopPane_MDI.add(form);
        form.setVisible(true);

    }// GEN-LAST:event_jMenuItem_nuevo_proveedorActionPerformed

    private void jMenuItem_gestionar_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_gestionar_proveedoresActionPerformed
        // TODO add your handling code here:

        Vistas.FrmGestionarProveedores form = new Vistas.FrmGestionarProveedores();
        Modelos.Proveedor proveedor = new Modelos.Proveedor();
        Modelos.ProveedorDAO dao = new Modelos.ProveedorDAO();
        Controladores.CtrlProveedor.CtrlGestionarProveedores ctrl = new Controladores.CtrlProveedor.CtrlGestionarProveedores(
                proveedor, form, dao);

        ctrl.cargarTabla();
        jDesktopPane_MDI.add(form);
        form.setVisible(true);
    }// GEN-LAST:event_jMenuItem_gestionar_proveedoresActionPerformed

    private void jMenuItem_nuevo_productoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_nuevo_productoActionPerformed
        // TODO add your handling code here:
        FrmNuevoProducto vista = new FrmNuevoProducto();
        jDesktopPane_MDI.add(vista);
        NuevoProductoController controlador = new NuevoProductoController(vista);
        vista.setVisible(true);
    }// GEN-LAST:event_jMenuItem_nuevo_productoActionPerformed

    private void jMenuItem_gestionar_productoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_gestionar_productoActionPerformed
        // TODO add your handling code here:
        FrmGestionarProductos vista = new FrmGestionarProductos();
        jDesktopPane_MDI.add(vista);
        GestionProductosController controlador = new GestionProductosController(vista);
        vista.setVisible(true);
    }// GEN-LAST:event_jMenuItem_gestionar_productoActionPerformed

    private void jMenuItem_ajuste_inventarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem_ajuste_inventarioActionPerformed
        // TODO add your handling code here:
        FrmAjusteInventario vista = new FrmAjusteInventario();
        jDesktopPane_MDI.add(vista);
        AjusteInventarioController controlador = new AjusteInventarioController(vista);

        vista.setVisible(true);
    }// GEN-LAST:event_jMenuItem_ajuste_inventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MDI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem_ajuste_inventario;
    private javax.swing.JMenuItem jMenuItem_gestionar_producto;
    private javax.swing.JMenuItem jMenuItem_gestionar_proveedores;
    private javax.swing.JMenuItem jMenuItem_nuevo_producto;
    private javax.swing.JMenuItem jMenuItem_nuevo_proveedor;
    private javax.swing.JMenu jMenu_producto;
    private javax.swing.JMenu jMenu_proveedores;
    // End of variables declaration//GEN-END:variables
}
